services:
  cloak:
    # image: ghcr.io/dpidetector/dpidetector-cloak
    image: dpidetector/dpidetector-cloak
    build:
      context: .
      dockerfile: ./protos/cloak/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    restart: on-failure:3

  shadowsocks:
    # image: ghcr.io/dpidetector/dpidetector-shadowsocks
    image: dpidetector/dpidetector-shadowsocks
    build:
      context: .
      dockerfile: ./protos/shadowsocks/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    restart: on-failure:3

  amnezia-wireguard:
    # image: ghcr.io/dpidetector/dpidetector-amnezia-wireguard
    image: dpidetector/dpidetector-amnezia-wireguard
    build:
      context: .
      dockerfile: ./protos/amnezia-wireguard/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: on-failure:3

  wireguard:
    # image: ghcr.io/dpidetector/dpidetector-wireguard
    image: dpidetector/dpidetector-wireguard
    build:
      context: .
      dockerfile: ./protos/wireguard/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    cap_add:
      - NET_ADMIN
    restart: on-failure:3

  openvpn-tlscrypt:
    # image: ghcr.io/dpidetector/dpidetector-openvpn-tlscrypt
    image: dpidetector/dpidetector-openvpn-tlscrypt
    build:
      context: .
      dockerfile: ./protos/openvpn-tlscrypt/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: on-failure:3

  openvpn:
    # image: ghcr.io/dpidetector/dpidetector-openvpn
    image: dpidetector/dpidetector-openvpn
    build:
      context: .
      dockerfile: ./protos/openvpn/Dockerfile
    env_file:
      - "user.conf"
    logging:
      driver: json-file
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: on-failure:3
