name: Build and push images for merged PR (for testing purposes)

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        proto: [cloak, shadowsocks, wireguard, amnezia-wireguard, openvpn, openvpn-tlscrypt, anyconnect]
    steps:
    - id: fixes
      uses: actions/github-script@v7
      with:
        script: |
          core.setOutput('owner', '${{ github.repository_owner }}'.toLowerCase());
          core.setOutput('pr', '${{ github.ref_name }}'.toLowerCase().replaceAll(/[/].*/g, '').replaceAll(/[.]/g, '-').trim('-'));

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DKRUSR }}
        password: ${{ secrets.DKRTKN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHTKN }}

    - name: Create VERSION file
      run: echo "${{ steps.fixes.outputs.pr }}" > VERSION

    - name: Build Containers and push them to registries (GHCR & DockerHub)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./protos/${{ matrix.proto }}/Dockerfile
        platforms:
          linux/amd64,
          linux/arm/v7,
          linux/arm64/v8,
          linux/386,
          linux/ppc64le,
        #  linux/riscv64
        # Will be available on alpine 3.20
        tags: |
          ghcr.io/${{ steps.fixes.outputs.owner }}/node-${{ matrix.proto }}:${{ steps.fixes.outputs.pr }}
          ${{ steps.fixes.outputs.owner }}/node-${{ matrix.proto }}:${{ steps.fixes.outputs.pr }}
        push: true
